name: Sync Changes

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  repository_dispatch:
    types: [sync-event]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Fetch all branches
        run: |
          git fetch --prune --unshallow
          
      - name: Auto-sync changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          
          # 원격 변경사항 가져오기
          git pull origin main --rebase
          
          # 로컬 변경사항 푸시
          git push origin main
